=== bizneststore/server/game/config/network/ClientPacketFilter.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="packets">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="packetByName">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="limit">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="log">
                      <xs:complexType>
                        <xs:attribute name="format" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" name="actionFailed" />
                    <xs:element minOccurs="0" name="drop" />
                  </xs:sequence>
                  <xs:attribute name="count" type="xs:unsignedByte" use="required" />
                  <xs:attribute name="perMs" type="xs:unsignedShort" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== bizneststore/server/game/config/network/ClientPacketFilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<packets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./ClientPacketFilter.xsd">
    <!-- DO NOT TOUCH THIS PACKET! -->
    <packetByName name="MoveBackwardToLocation">
        <limit count="4" perMs="1000">
<!--             <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit MoveBackwardToLocation"/> -->
            <!-- <msg text="Dont do it that often"/> -->
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <!-- DO NOT TOUCH THIS PACKET! -->
    <packetByName name="RequestMagicSkillUse">
        <limit count="20" perMs="1000">
<!--             <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit RequestMagicSkillUse"/> -->
            <!-- <msg text="Dont do it that often"/> -->
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <!-- DO NOT TOUCH THIS PACKET! -->
    <packetByName name="Appearing">
        <limit count="3" perMs="1000">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit Appearing"/>
            <!-- <msg text="Dont do it that often"/> -->
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <!-- DO NOT TOUCH THIS PACKET! -->
    <packetByName name="AttackRequest">
        <limit count="1" perMs="300">
            <!-- <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit AttackRequest"/> -->
            <!-- <msg text="Dont do it that often"/> -->
            <actionFailed/>
            <!-- <drop/> -->
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <!-- DO NOT TOUCH THIS PACKET! -->
    <packetByName name="RequestEnchantItem">
        <limit count="1" perMs="500">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit RequestEnchantItem"/>
            <actionFailed/>
            <!-- <drop/> -->
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <!-- DO NOT TOUCH THIS PACKET! -->
    <packetByName name="RequestDropItem">
        <limit count="2" perMs="300">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit RequestDropItem"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <!-- DO NOT TOUCH THIS PACKET! -->
    <packetByName name="RequestPledgeCrest">
        <limit count="30" perMs="100">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit RequestPledgeCrest"/>
            <!-- <actionFailed/> -->
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <!-- DO NOT TOUCH THIS PACKET! -->
    <packetByName name="RequestSetPledgeCrest">
        <limit count="1" perMs="500">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit RequestSetPledgeCrest"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <!-- DO NOT TOUCH THIS PACKET! -->
    <packetByName name="EnterWorld">
        <limit count="2" perMs="1200">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit EnterWorld"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <!-- You can modify these packages for yourself -->
    <packetByName name="Logout">
        <limit count="1" perMs="100">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit Logout"/>
            <actionFailed/>
            <!-- <drop/> -->
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="RequestStartPledgeWar">
        <limit count="1" perMs="800">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit RequestStartPledgeWar"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="RequestStopPledgeWar">
        <limit count="1" perMs="800">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit RequestStopPledgeWar"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="RequestGiveNickName">
        <limit count="1" perMs="800">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit RequestGiveNickName"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="CharacterCreate">
        <limit count="1" perMs="1200">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit CharacterCreate"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="CharacterDelete">
        <limit count="1" perMs="1200">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit CharacterDelete"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="ProtocolVersion">
        <limit count="1" perMs="600">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit ProtocolVersion"/>
            <actionFailed/>
            <!-- <drop/> -->
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="CharacterSelect">
        <limit count="2" perMs="1200">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit CharacterSelect"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="NewCharacter">
        <limit count="2" perMs="2000">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit NewCharacter"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="TradeRequest">
        <limit count="1" perMs="300">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit TradeRequest"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="AddTradeItem">
        <limit count="1" perMs="300">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit AddTradeItem"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="TradeDone">
        <limit count="1" perMs="300">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit TradeDone"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="RequestBypassToServer">
        <limit count="1" perMs="100">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit RequestBypassToServer"/>
            <actionFailed/>
            <!-- <drop/> -->
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="RequestBBSwrite">
        <limit count="1" perMs="300">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit RequestBBSwrite"/>
            <actionFailed/>
            <!--<drop/>-->
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="RequestJoinPledge">
        <limit count="1" perMs="1000">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit RequestJoinPledge"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="RequestAnswerJoinPledge">
        <limit count="1" perMs="1000">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit RequestAnswerJoinPledge"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="RequestWithdrawalPledge">
        <limit count="1" perMs="1000">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit RequestWithdrawalPledge"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="RequestGetItemFromPet">
        <limit count="1" perMs="600">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit RequestGetItemFromPet"/>
            <actionFailed/>
            <!-- <drop/> -->
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="RequestCrystallizeItem">
        <limit count="1" perMs="300">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit RequestCrystallizeItem"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="RequestSellItem">
        <limit count="1" perMs="300">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit RequestSellItem"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="SendWareHouseWithDrawList">
        <limit count="1" perMs="500">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit SendWareHouseWithDrawList"/>
            <actionFailed/>
            <drop/>
            <!-- <kick/> -->
        </limit>
    </packetByName>
    <packetByName name="SendWareHouseDepositList">
        <limit count="1" perMs="500">
            <log format="Player %user_name%/%account_name%[%ip%/%hwid%] limit SendWareHouseDepositList"/>
            <actionFailed/>
            <drop/>
