=== bizneststore/server/game/data/xsd/fakeNpcs.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="list">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="npc" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:integer" name="npc_id"/>
              <xs:element type="xs:integer" name="race"/>
              <xs:element type="xs:integer" name="sex"/>
              <xs:element type="xs:integer" name="class"/>
              <xs:element type="xs:string" name="title"/>
              <xs:element type="xs:string" name="title_color"/>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:string" name="name_color"/>
              <xs:element type="xs:integer" name="hair_style"/>
              <xs:element type="xs:integer" name="hair_color"/>
              <xs:element type="xs:integer" name="face"/>
              <xs:element type="xs:byte" name="mount"/>
              <xs:element type="xs:byte" name="team"/>
              <xs:element type="xs:byte" name="hero"/>
              <xs:element type="xs:integer" name="pd_under"/>
              <xs:element type="xs:integer" name="pd_under_aug"/>
              <xs:element type="xs:integer" name="pd_head"/>
              <xs:element type="xs:integer" name="pd_head_aug"/>
              <xs:element type="xs:integer" name="pd_rhand"/>
              <xs:element type="xs:integer" name="pd_rhand_aug"/>
              <xs:element type="xs:integer" name="pd_lhand"/>
              <xs:element type="xs:integer" name="pd_lhand_aug"/>
              <xs:element type="xs:integer" name="pd_gloves"/>
              <xs:element type="xs:integer" name="pd_gloves_aug"/>
              <xs:element type="xs:integer" name="pd_chest"/>
              <xs:element type="xs:integer" name="pd_chest_aug"/>
              <xs:element type="xs:integer" name="pd_legs"/>
              <xs:element type="xs:integer" name="pd_legs_aug"/>
              <xs:element type="xs:integer" name="pd_feet"/>
              <xs:element type="xs:integer" name="pd_feet_aug"/>
              <xs:element type="xs:integer" name="pd_back"/>
              <xs:element type="xs:integer" name="pd_back_aug"/>
              <xs:element type="xs:integer" name="pd_lrhand"/>
              <xs:element type="xs:integer" name="pd_lrhand_aug"/>
              <xs:element type="xs:integer" name="pd_hair"/>
              <xs:element type="xs:integer" name="pd_hair_aug"/>
              <xs:element type="xs:integer" name="pd_hair2"/>
              <xs:element type="xs:integer" name="pd_hair2_aug"/>
              <xs:element type="xs:integer" name="pd_rbracelet"/>
              <xs:element type="xs:integer" name="pd_rbracelet_aug"/>
              <xs:element type="xs:integer" name="pd_lbracelet"/>
              <xs:element type="xs:integer" name="pd_lbracelet_aug"/>
              <xs:element type="xs:integer" name="pd_deco1"/>
              <xs:element type="xs:integer" name="pd_deco1_aug"/>
              <xs:element type="xs:integer" name="pd_deco2"/>
              <xs:element type="xs:integer" name="pd_deco2_aug"/>
              <xs:element type="xs:integer" name="pd_deco3"/>
              <xs:element type="xs:integer" name="pd_deco3_aug"/>
              <xs:element type="xs:integer" name="pd_deco4"/>
              <xs:element type="xs:integer" name="pd_deco4_aug"/>
              <xs:element type="xs:integer" name="pd_deco5"/>
              <xs:element type="xs:integer" name="pd_deco5_aug"/>
              <xs:element type="xs:integer" name="pd_deco6"/>
              <xs:element type="xs:integer" name="pd_deco6_aug"/>
              <xs:element type="xs:integer" name="enchant_effect"/>
              <xs:element type="xs:integer" name="pvp_flag"/>
              <xs:element type="xs:integer" name="karma"/>
              <xs:element type="xs:integer" name="fishing"/>
              <xs:element type="xs:integer" name="fishing_x"/>
              <xs:element type="xs:integer" name="fishing_y"/>
              <xs:element type="xs:integer" name="fishing_z"/>
              <xs:element type="xs:byte" name="invisible"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== bizneststore/server/game/data/xml/sunrise/fakeNpcs.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/fakeNpcs.xsd">
	<npc>
		<npc_id>50007</npc_id>
		<race>0</race>
		<sex>1</sex>
		<class>93</class>
		<title>www.l2jsunrise.com</title>
		<title_color>9CE8A9</title_color>
		<name>Wedding Manager</name>
		<name_color>FFFFFF</name_color>
		<hair_style>2</hair_style>
		<hair_color>2</hair_color>
		<face>1</face>
		<mount>0</mount>
		<team>0</team>
		<hero>1</hero>
		<pd_under>0</pd_under>
		<pd_under_aug>0</pd_under_aug>
		<pd_head>0</pd_head>
		<pd_head_aug>0</pd_head_aug>
		<pd_rhand>21163</pd_rhand>
		<pd_rhand_aug>1</pd_rhand_aug>
		<pd_lhand>0</pd_lhand>
		<pd_lhand_aug>0</pd_lhand_aug>
		<pd_gloves>0</pd_gloves>
		<pd_gloves_aug>0</pd_gloves_aug>
		<pd_chest>6408</pd_chest>
		<pd_chest_aug>0</pd_chest_aug>
		<pd_legs>0</pd_legs>
		<pd_legs_aug>0</pd_legs_aug>
		<pd_feet>0</pd_feet>
		<pd_feet_aug>0</pd_feet_aug>
		<pd_back>0</pd_back>
		<pd_back_aug>0</pd_back_aug>
		<pd_lrhand>0</pd_lrhand>
		<pd_lrhand_aug>0</pd_lrhand_aug>
		<pd_hair>6841</pd_hair>
		<pd_hair_aug>0</pd_hair_aug>
		<pd_hair2>0</pd_hair2>
		<pd_hair2_aug>0</pd_hair2_aug>
		<pd_rbracelet>0</pd_rbracelet>
		<pd_rbracelet_aug>0</pd_rbracelet_aug>
		<pd_lbracelet>0</pd_lbracelet>
		<pd_lbracelet_aug>0</pd_lbracelet_aug>
		<pd_deco1>0</pd_deco1>
		<pd_deco1_aug>0</pd_deco1_aug>
		<pd_deco2>0</pd_deco2>
		<pd_deco2_aug>0</pd_deco2_aug>
		<pd_deco3>0</pd_deco3>
		<pd_deco3_aug>0</pd_deco3_aug>
		<pd_deco4>0</pd_deco4>
		<pd_deco4_aug>0</pd_deco4_aug>
		<pd_deco5>0</pd_deco5>
		<pd_deco5_aug>0</pd_deco5_aug>
		<pd_deco6>0</pd_deco6>
		<pd_deco6_aug>0</pd_deco6_aug>
		<enchant_effect>0</enchant_effect>
		<pvp_flag>0</pvp_flag>
		<karma>0</karma>
		<fishing>0</fishing>
		<fishing_x>0</fishing_x>
		<fishing_y>0</fishing_y>
		<fishing_z>0</fishing_z>
		<invisible>0</invisible>
	</npc>
	<npc>
		<npc_id>560</npc_id>
		<race>0</race>
		<sex>1</sex>
		<class>2</class>
		<title>www.l2jsunrise.com</title>
		<title_color>9CE8A9</title_color>
		<name>Delevel Manager</name>
		<name_color>FFFFFF</name_color>
		<hair_style>2</hair_style>
		<hair_color>1</hair_color>
		<face>1</face>
		<mount>0</mount>
		<team>0</team>
		<hero>0</hero>
		<pd_under>0</pd_under>
		<pd_under_aug>0</pd_under_aug>
		<pd_head>0</pd_head>
		<pd_head_aug>0</pd_head_aug>
		<pd_rhand>2591</pd_rhand>
		<pd_rhand_aug>0</pd_rhand_aug>
		<pd_lhand>0</pd_lhand>
		<pd_lhand_aug>0</pd_lhand_aug>
		<pd_gloves>2462</pd_gloves>
		<pd_gloves_aug>0</pd_gloves_aug>
		<pd_chest>356</pd_chest>
		<pd_chest_aug>0</pd_chest_aug>
		<pd_legs>0</pd_legs>
		<pd_legs_aug>0</pd_legs_aug>
		<pd_feet>2438</pd_feet>
		<pd_feet_aug>0</pd_feet_aug>
		<pd_back>0</pd_back>
		<pd_back_aug>0</pd_back_aug>
		<pd_lrhand>0</pd_lrhand>
		<pd_lrhand_aug>0</pd_lrhand_aug>
		<pd_hair>0</pd_hair>
		<pd_hair_aug>0</pd_hair_aug>
		<pd_hair2>0</pd_hair2>
		<pd_hair2_aug>0</pd_hair2_aug>
		<pd_rbracelet>0</pd_rbracelet>
		<pd_rbracelet_aug>0</pd_rbracelet_aug>
		<pd_lbracelet>0</pd_lbracelet>
		<pd_lbracelet_aug>0</pd_lbracelet_aug>
		<pd_deco1>0</pd_deco1>
		<pd_deco1_aug>0</pd_deco1_aug>
		<pd_deco2>0</pd_deco2>
		<pd_deco2_aug>0</pd_deco2_aug>
		<pd_deco3>0</pd_deco3>
		<pd_deco3_aug>0</pd_deco3_aug>
		<pd_deco4>0</pd_deco4>
		<pd_deco4_aug>0</pd_deco4_aug>
		<pd_deco5>0</pd_deco5>
		<pd_deco5_aug>0</pd_deco5_aug>
		<pd_deco6>0</pd_deco6>
		<pd_deco6_aug>0</pd_deco6_aug>
		<enchant_effect>0</enchant_effect>
		<pvp_flag>0</pvp_flag>
		<karma>0</karma>
		<fishing>0</fishing>
		<fishing_x>0</fishing_x>
		<fishing_y>0</fishing_y>
		<fishing_z>0</fishing_z>
		<invisible>0</invisible>
	</npc>
	<npc>
		<npc_id>559</npc_id>
		<race>3</race>
		<sex>0</sex>
		<class>114</class>
		<title>www.l2jsunrise.com</title>
		<title_color>9CE8A9</title_color>
		<name>Beta Npc</name>
		<name_color>FFFFFF</name_color>
		<hair_style>2</hair_style>
		<hair_color>1</hair_color>
		<face>1</face>
		<mount>0</mount>
		<team>0</team>
		<hero>0</hero>
		<pd_under>0</pd_under>
		<pd_under_aug>0</pd_under_aug>
		<pd_head>0</pd_head>
		<pd_head_aug>0</pd_head_aug>
		<pd_rhand>15556</pd_rhand>
		<pd_rhand_aug>0</pd_rhand_aug>
		<pd_lhand>0</pd_lhand>
		<pd_lhand_aug>0</pd_lhand_aug>
		<pd_gloves>15582</pd_gloves>
		<pd_gloves_aug>0</pd_gloves_aug>
		<pd_chest>16169</pd_chest>
		<pd_chest_aug>0</pd_chest_aug>
		<pd_legs>15579</pd_legs>
		<pd_legs_aug>0</pd_legs_aug>
		<pd_feet>15585</pd_feet>
		<pd_feet_aug>0</pd_feet_aug>
		<pd_back>21717</pd_back>
		<pd_back_aug>0</pd_back_aug>
		<pd_lrhand>0</pd_lrhand>
		<pd_lrhand_aug>0</pd_lrhand_aug>
		<pd_hair>0</pd_hair>
		<pd_hair_aug>0</pd_hair_aug>
		<pd_hair2>0</pd_hair2>
		<pd_hair2_aug>0</pd_hair2_aug>
		<pd_rbracelet>0</pd_rbracelet>
		<pd_rbracelet_aug>0</pd_rbracelet_aug>
		<pd_lbracelet>0</pd_lbracelet>
		<pd_lbracelet_aug>0</pd_lbracelet_aug>
		<pd_deco1>0</pd_deco1>
		<pd_deco1_aug>0</pd_deco1_aug>
		<pd_deco2>0</pd_deco2>
		<pd_deco2_aug>0</pd_deco2_aug>
		<pd_deco3>0</pd_deco3>
		<pd_deco3_aug>0</pd_deco3_aug>
		<pd_deco4>0</pd_deco4>
		<pd_deco4_aug>0</pd_deco4_aug>
		<pd_deco5>0</pd_deco5>
		<pd_deco5_aug>0</pd_deco5_aug>
		<pd_deco6>0</pd_deco6>
		<pd_deco6_aug>0</pd_deco6_aug>
		<enchant_effect>0</enchant_effect>
		<pvp_flag>0</pvp_flag>
		<karma>0</karma>
		<fishing>0</fishing>
		<fishing_x>0</fishing_x>
		<fishing_y>0</fishing_y>
		<fishing_z>0</fishing_z>
		<invisible>0</invisible>
	</npc>
	<npc>
		<npc_id>556</npc_id>
		<race>3</race>
		<sex>0</sex>
		<class>114</class>
		<title>www.l2jsunrise.com</title>
		<title_color>9CE8A9</title_color>
		<name>Black Market</name>
		<name_color>FFFFFF</name_color>
		<hair_style>2</hair_style>
		<hair_color>2</hair_color>
		<face>1</face>
		<mount>0</mount>
		<team>0</team>
		<hero>0</hero>
		<pd_under>0</pd_under>
		<pd_under_aug>0</pd_under_aug>
		<pd_head>0</pd_head>
		<pd_head_aug>0</pd_head_aug>
		<pd_rhand>6371</pd_rhand>
		<pd_rhand_aug>0</pd_rhand_aug>
		<pd_lhand>0</pd_lhand>
		<pd_lhand_aug>0</pd_lhand_aug>
		<pd_gloves>5768</pd_gloves>
		<pd_gloves_aug>0</pd_gloves_aug>
		<pd_chest>2382</pd_chest>
		<pd_chest_aug>0</pd_chest_aug>
		<pd_legs>0</pd_legs>
		<pd_legs_aug>0</pd_legs_aug>
		<pd_feet>5780</pd_feet>
		<pd_feet_aug>0</pd_feet_aug>
		<pd_back>0</pd_back>
		<pd_back_aug>0</pd_back_aug>
		<pd_lrhand>0</pd_lrhand>
		<pd_lrhand_aug>0</pd_lrhand_aug>
		<pd_hair>0</pd_hair>
		<pd_hair_aug>0</pd_hair_aug>
		<pd_hair2>0</pd_hair2>
		<pd_hair2_aug>0</pd_hair2_aug>
		<pd_rbracelet>0</pd_rbracelet>
		<pd_rbracelet_aug>0</pd_rbracelet_aug>
		<pd_lbracelet>0</pd_lbracelet>
		<pd_lbracelet_aug>0</pd_lbracelet_aug>
		<pd_deco1>0</pd_deco1>
		<pd_deco1_aug>0</pd_deco1_aug>
		<pd_deco2>0</pd_deco2>
		<pd_deco2_aug>0</pd_deco2_aug>
		<pd_deco3>0</pd_deco3>
		<pd_deco3_aug>0</pd_deco3_aug>
		<pd_deco4>0</pd_deco4>
		<pd_deco4_aug>0</pd_deco4_aug>
		<pd_deco5>0</pd_deco5>
		<pd_deco5_aug>0</pd_deco5_aug>
		<pd_deco6>0</pd_deco6>
		<pd_deco6_aug>0</pd_deco6_aug>
		<enchant_effect>0</enchant_effect>
		<pvp_flag>0</pvp_flag>
		<karma>0</karma>
		<fishing>0</fishing>
		<fishing_x>0</fishing_x>
		<fishing_y>0</fishing_y>
		<fishing_z>0</fishing_z>
		<invisible>0</invisible>
	</npc>
	<npc>
		<npc_id>555</npc_id>
		<race>5</race>
		<sex>1</sex>
		<class>132</class>
		<title>www.l2jsunrise.com</title>
		<title_color>9CE8A9</title_color>
		<name>Buffer</name>
		<name_color>FFFFFF</name_color>
		<hair_style>4</hair_style>
		<hair_color>2</hair_color>
		<face>1</face>
		<mount>0</mount>
		<team>0</team>
		<hero>0</hero>
		<pd_under>0</pd_under>
		<pd_under_aug>0</pd_under_aug>
		<pd_head>0</pd_head>
		<pd_head_aug>0</pd_head_aug>
		<pd_rhand>133</pd_rhand>
		<pd_rhand_aug>0</pd_rhand_aug>
		<pd_lhand>0</pd_lhand>
		<pd_lhand_aug>0</pd_lhand_aug>
		<pd_gloves>6380</pd_gloves>
		<pd_gloves_aug>0</pd_gloves_aug>
		<pd_chest>6379</pd_chest>
		<pd_chest_aug>0</pd_chest_aug>
		<pd_legs>0</pd_legs>
		<pd_legs_aug>0</pd_legs_aug>
		<pd_feet>6381</pd_feet>
		<pd_feet_aug>0</pd_feet_aug>
		<pd_back>0</pd_back>
		<pd_back_aug>0</pd_back_aug>
		<pd_lrhand>0</pd_lrhand>
		<pd_lrhand_aug>0</pd_lrhand_aug>
		<pd_hair>0</pd_hair>
		<pd_hair_aug>0</pd_hair_aug>
		<pd_hair2>0</pd_hair2>
		<pd_hair2_aug>0</pd_hair2_aug>
		<pd_rbracelet>0</pd_rbracelet>
		<pd_rbracelet_aug>0</pd_rbracelet_aug>
		<pd_lbracelet>0</pd_lbracelet>
		<pd_lbracelet_aug>0</pd_lbracelet_aug>
		<pd_deco1>0</pd_deco1>
		<pd_deco1_aug>0</pd_deco1_aug>
		<pd_deco2>0</pd_deco2>
		<pd_deco2_aug>0</pd_deco2_aug>
		<pd_deco3>0</pd_deco3>
		<pd_deco3_aug>0</pd_deco3_aug>
		<pd_deco4>0</pd_deco4>
		<pd_deco4_aug>0</pd_deco4_aug>
		<pd_deco5>0</pd_deco5>
		<pd_deco5_aug>0</pd_deco5_aug>
		<pd_deco6>0</pd_deco6>
		<pd_deco6_aug>0</pd_deco6_aug>
		<enchant_effect>0</enchant_effect>
		<pvp_flag>0</pvp_flag>
		<karma>0</karma>
		<fishing>0</fishing>
		<fishing_x>0</fishing_x>
		<fishing_y>0</fishing_y>
		<fishing_z>0</fishing_z>
		<invisible>0</invisible>
	</npc>
	<npc>
		<npc_id>554</npc_id>
		<race>0</race>
		<sex>0</sex>
		<class>5</class>
		<title>www.l2jsunrise.com</title>
		<title_color>9CE8A9</title_color>
		<name>Points Manager</name>
		<name_color>FFFFFF</name_color>
		<hair_style>4</hair_style>
		<hair_color>2</hair_color>
		<face>1</face>
		<mount>0</mount>
		<team>0</team>
		<hero>0</hero>
		<pd_under>0</pd_under>
		<pd_under_aug>0</pd_under_aug>
		<pd_head>0</pd_head>
		<pd_head_aug>0</pd_head_aug>
		<pd_rhand>6364</pd_rhand>
		<pd_rhand_aug>0</pd_rhand_aug>
		<pd_lhand>0</pd_lhand>
		<pd_lhand_aug>0</pd_lhand_aug>
		<pd_gloves>6375</pd_gloves>
		<pd_gloves_aug>0</pd_gloves_aug>
		<pd_chest>6373</pd_chest>
		<pd_chest_aug>0</pd_chest_aug>
		<pd_legs>6374</pd_legs>
		<pd_legs_aug>0</pd_legs_aug>
		<pd_feet>6376</pd_feet>
		<pd_feet_aug>0</pd_feet_aug>
		<pd_back>0</pd_back>
		<pd_back_aug>0</pd_back_aug>
		<pd_lrhand>0</pd_lrhand>
		<pd_lrhand_aug>0</pd_lrhand_aug>
		<pd_hair>0</pd_hair>
		<pd_hair_aug>0</pd_hair_aug>
		<pd_hair2>0</pd_hair2>
		<pd_hair2_aug>0</pd_hair2_aug>
