=== bizneststore/server/game/data/xml/retail/xsd/fishingData.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="fishingData">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="distribution" maxOccurs="unbounded"
					minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="xs:byte" name="distribution_id"
									use="optional" />
								<xs:attribute type="xs:string" name="default_distribution"
									use="optional" />
								<xs:attribute type="xs:string" name="night_fishing_distribution"
									use="optional" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="fishing_place" maxOccurs="unbounded"
					minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="xs:byte" name="fishing_place_id"
									use="optional" />
								<xs:attribute type="xs:string" name="territory"
									use="optional" />
								<xs:attribute type="xs:short" name="limit_grid"
									use="optional" />
								<xs:attribute type="xs:byte" name="distribution_id"
									use="optional" />
								<xs:attribute type="xs:string" name="fishing_place_type"
									use="optional" />
								<xs:attribute type="xs:byte" name="maintain_distribution_time"
									use="optional" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="lure" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="xs:byte" name="lure_id" use="optional" />
								<xs:attribute type="xs:short" name="lure_item_id"
									use="optional" />
								<xs:attribute type="xs:float" name="revision_number"
									use="optional" />
								<xs:attribute type="xs:short" name="length_bonus"
									use="optional" />
								<xs:attribute type="xs:float" name="length_rate_bonus"
									use="optional" />
								<xs:attribute type="xs:string" name="lure_type"
									use="optional" />
								<xs:attribute type="xs:string" name="fish_group_preference"
									use="optional" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="fish" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="xs:short" name="fish_id" use="optional" />
								<xs:attribute type="xs:short" name="item_id" use="optional" />
								<xs:attribute type="xs:string" name="item_name"
									use="optional" />
								<xs:attribute type="xs:string" name="fish_group"
									use="optional" />
								<xs:attribute type="xs:byte" name="fish_level" use="optional" />
								<xs:attribute type="xs:float" name="fish_bite_rate"
									use="optional" />
								<xs:attribute type="xs:float" name="fish_guts" use="optional" />
								<xs:attribute type="xs:short" name="fish_hp" use="optional" />
								<xs:attribute type="xs:short" name="fish_max_length"
									use="optional" />
								<xs:attribute type="xs:float" name="fish_length_rate"
									use="optional" />
								<xs:attribute type="xs:float" name="hp_regen" use="optional" />
								<xs:attribute type="xs:byte" name="start_combat_time"
									use="optional" />
								<xs:attribute type="xs:byte" name="combat_duration"
									use="optional" />
								<xs:attribute type="xs:byte" name="guts_check_time"
									use="optional" />
								<xs:attribute type="xs:float" name="guts_check_probability"
									use="optional" />
								<xs:attribute type="xs:float" name="cheating_prob"
									use="optional" />
								<xs:attribute type="xs:string" name="fish_grade"
									use="optional" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="fishingrod" maxOccurs="unbounded"
					minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="xs:byte" name="fishingrod_id"
									use="optional" />
								<xs:attribute type="xs:short" name="fishingrod_item_id"
									use="optional" />
								<xs:attribute type="xs:byte" name="fishingrod_level"
									use="optional" />
								<xs:attribute type="xs:string" name="fishingrod_name"
									use="optional" />
								<xs:attribute type="xs:float" name="fishingrod_damage"
									use="optional" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="fishingmonster" maxOccurs="unbounded"
					minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="xs:string" name="user_level"
									use="optional" />
								<xs:attribute type="xs:float" name="monster_probability"
									use="optional" />
								<xs:attribute type="xs:short" name="fishingmonsters"
									use="optional" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== bizneststore/server/game/data/xml/retail/h5/fishingData.xml
<?xml version="1.0" encoding="UTF-8"?>
<fishingData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/fishingData.xsd">
	<distribution	distribution_id="1"	default_distribution="{{easy_wide;10};{easy_swift;10};{easy_ugly;10};{wide;10};{swift;10};{ugly;10};{fish_box;1}}"	night_fishing_distribution="{{easy_wide;10};{easy_swift;10};{easy_ugly;10};{wide;10};{swift;10};{ugly;10};{hard_wide;10};{hard_swift;10};{hard_ugly;10};{fish_box;5}}"	/>
	<distribution	distribution_id="2"	default_distribution="{{easy_wide;15};{easy_swift;15};{easy_ugly;15};{wide;15};{swift;15};{ugly;15};{fish_box;5}}"	night_fishing_distribution="{{easy_wide;10};{easy_swift;10};{easy_ugly;10};{wide;10};{swift;10};{ugly;10};{hard_wide;10};{hard_swift;10};{hard_ugly;10};{fish_box;5}}"	/>
	<distribution	distribution_id="3"	default_distribution="{{easy_wide;15};{easy_swift;15};{easy_ugly;15};{wide;15};{swift;15};{ugly;15};{fish_box;5}}"	night_fishing_distribution="{{easy_wide;10};{easy_swift;10};{easy_ugly;10};{wide;10};{swift;10};{ugly;10};{hard_wide;10};{hard_swift;10};{hard_ugly;10};{fish_box;5}}"	/>
	<distribution	distribution_id="4"	default_distribution="{{easy_wide;14};{easy_swift;14};{easy_ugly;14};{wide;14};{swift;14};{ugly;14};{fish_box;5};{hs_fish;5}}"	night_fishing_distribution="{{easy_wide;9};{easy_swift;9};{easy_ugly;9};{wide;9};{swift;9};{ugly;9};{hard_wide;9};{hard_swift;9};{hard_ugly;9};{hs_fish;9};{fish_box;5}}"	/>
	<fishing_place	fishing_place_id="1"	territory="{{141249;-109636;-3634;-3434};{141473;-109798;-3634;-3434};{141739;-109821;-3634;-3434};{141924;-109669;-3634;-3434};{142038;-109397;-3634;-3434};{141852;-109130;-3634;-3434};{141604;-109051;-3634;-3434};{141321;-109091;-3634;-3434};{141213;-109266;-3634;-3434}}"	limit_grid="1000"	distribution_id="1"	fishing_place_type="fishing_place_default"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="2"	territory="{{141249;-109636;-3634;-3434};{141473;-109798;-3634;-3434};{141739;-109821;-3634;-3434};{141924;-109669;-3634;-3434};{142038;-109397;-3634;-3434};{141852;-109130;-3634;-3434};{141604;-109051;-3634;-3434};{141321;-109091;-3634;-3434};{141213;-109266;-3634;-3434}}"	limit_grid="1000"	distribution_id="4"	fishing_place_type="fishing_place_type2"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="3"	territory="{{140174;-105832;-3668;-3468};{140490;-105875;-3668;-3468};{140962;-105738;-3668;-3468};{141039;-105378;-3668;-3468};{140872;-105119;-3668;-3468};{140081;-105295;-3668;-3468}}"	limit_grid="1000"	distribution_id="4"	fishing_place_type="fishing_place_type2"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="4"	territory="{{144927;-105193;-3724;-3524};{145226;-105412;-3724;-3524};{145576;-105344;-3724;-3524};{145819;-104976;-3724;-3524};{145575;-104555;-3724;-3524};{145217;-104490;-3724;-3524};{144935;-104684;-3724;-3524};{144832;-104959;-3724;-3524}}"	limit_grid="1000"	distribution_id="4"	fishing_place_type="fishing_place_type2"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="5"	territory="{{152081;-108262;-2871;-2671};{152455;-108588;-2871;-2671};{152835;-108448;-2871;-2671};{152992;-108120;-2871;-2671};{152817;-107670;-2871;-2671};{152310;-107632;-2871;-2671};{152069;-107905;-2871;-2671}}"	limit_grid="1000"	distribution_id="4"	fishing_place_type="fishing_place_type2"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="6"	territory="{{155279;-105735;-2787;-2587};{155448;-105880;-2787;-2587};{155992;-105963;-2787;-2587};{156201;-105790;-2787;-2587};{156133;-105320;-2787;-2587};{155896;-105229;-2787;-2587};{155459;-105254;-2787;-2587};{155283;-105478;-2787;-2587}}"	limit_grid="1000"	distribution_id="4"	fishing_place_type="fishing_place_type2"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="7"	territory="{{156838;-109948;-2717;-2517};{157133;-110046;-2717;-2517};{157436;-109918;-2717;-2517};{157491;-109405;-2717;-2517};{157197;-109197;-2717;-2517};{156843;-109261;-2717;-2517};{156683;-109569;-2717;-2517}}"	limit_grid="1000"	distribution_id="4"	fishing_place_type="fishing_place_type2"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="8"	territory="{{152063;-116732;-1609;-1409};{152505;-116982;-1609;-1409};{152904;-116927;-1609;-1409};{153020;-116469;-1609;-1409};{152881;-116221;-1609;-1409};{152555;-116100;-1609;-1409};{152285;-116160;-1609;-1409};{152099;-116415;-1609;-1409}}"	limit_grid="1000"	distribution_id="4"	fishing_place_type="fishing_place_type2"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="9"	territory="{{152683;-112829;-1694;-1494};{152796;-113129;-1694;-1494};{153125;-113339;-1694;-1494};{153557;-113190;-1694;-1494};{153649;-112721;-1694;-1494};{153344;-112385;-1694;-1494};{152937;-112409;-1694;-1494}}"	limit_grid="1000"	distribution_id="4"	fishing_place_type="fishing_place_type2"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="10"	territory="{{157444;-115790;-1979;-1779};{157774;-115907;-1979;-1779};{158174;-115759;-1979;-1779};{158017;-114971;-1979;-1779};{157625;-114984;-1979;-1779};{157439;-115101;-1979;-1779}}"	limit_grid="1000"	distribution_id="4"	fishing_place_type="fishing_place_type2"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="11"	territory="{{147182;-113255;-2152;-1952};{147194;-113430;-2152;-1952};{147312;-113584;-2152;-1952};{147467;-113630;-2152;-1952};{147748;-113523;-2152;-1952};{147816;-113273;-2152;-1952};{147723;-113074;-2152;-1952};{147512;-112956;-2152;-1952};{147258;-113048;-2152;-1952}}"	limit_grid="1000"	distribution_id="4"	fishing_place_type="fishing_place_type2"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="12"	territory="{{35360;70052;-4388;-1388};{54640;70780;-4388;-1388};{58104;89528;-4388;-1388};{38900;91644;-4388;-1388}}"	limit_grid="1000"	distribution_id="2"	fishing_place_type="fishing_place_type1"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="13"	territory="{{-99139;207208;-4916;-1916};{-65905;254858;-4916;-1916};{-65905;261841;-4916;-1916};{-124577;261607;-4916;-1916};{-128220;215665;-4916;-1916}}"	limit_grid="1000"	distribution_id="2"	fishing_place_type="fishing_place_type1"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="14"	territory="{{134452;66180;-4640;-1640};{170228;67184;-4640;-1640};{172464;97052;-4640;-1640};{136188;94940;-4640;-1640}}"	limit_grid="1000"	distribution_id="2"	fishing_place_type="fishing_place_type1"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="15"	territory="{{135800;35476;-4216;-1216};{162960;35364;-4216;-1216};{161056;64920;-4216;-1216};{136496;65092;-4216;-1216}}"	limit_grid="1000"	distribution_id="2"	fishing_place_type="fishing_place_type1"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="16"	territory="{{97311;-229576;-2568;1432};{201955;-229291;-2568;1432};{201926;-163450;-2568;1432};{97636;-164202;-2568;1432}}"	limit_grid="1000"	distribution_id="2"	fishing_place_type="fishing_place_type1"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="17"	territory="{{89909;158343;-7356;-1356};{130731;153447;-7356;-1356};{130741;261840;-7356;-1356};{65549;262183;-7356;-1356};{65612;189166;-7356;-1356}}"	limit_grid="1000"	distribution_id="2"	fishing_place_type="fishing_place_type1"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="18"	territory="{{81328;136658;-3892;-892};{139003;123356;-3892;-892};{138584;145204;-3892;-892};{121150;155944;-3892;-892};{80807;160436;-3892;-892}}"	limit_grid="1000"	distribution_id="2"	fishing_place_type="fishing_place_type1"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="19"	territory="{{67326;160359;-4684;-1684};{86813;160109;-4684;-1684};{64159;189723;-4684;-1684};{42375;183029;-4684;-1684}}"	limit_grid="1000"	distribution_id="2"	fishing_place_type="fishing_place_type1"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="20"	territory="{{30606;184275;-4874;-1874};{40957;182824;-4874;-1874};{62226;189792;-4874;-1874};{62509;228946;-4874;-1874};{30706;228846;-4874;-1874}}"	limit_grid="1000"	distribution_id="2"	fishing_place_type="fishing_place_type1"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="21"	territory="{{65472;71452;-4372;-1372};{86420;82248;-4372;-1372};{97656;93300;-4372;-1372};{97692;98032;-4372;-1372};{64528;97660;-4372;-1372}}"	limit_grid="1000"	distribution_id="2"	fishing_place_type="fishing_place_type1"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="22"	territory="{{66204;3448;-4328;-1328};{121052;30384;-4328;-1328};{87064;56664;-4328;-1328};{69484;31724;-4328;-1328}}"	limit_grid="1000"	distribution_id="2"	fishing_place_type="fishing_place_type1"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="23"	territory="{{4721;99932;-4096;-1096};{60654;99812;-4096;-1096};{60606;158582;-4096;-1096};{40546;154557;-4096;-1096};{3147;123027;-4096;-1096}}"	limit_grid="1000"	distribution_id="2"	fishing_place_type="fishing_place_type1"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="24"	territory="{{36902;-98025;-4724;-1724};{9543;-42544;-4724;-1724};{54988;-7732;-4724;-1724};{96957;-65614;-4724;-1724}}"	limit_grid="1000"	distribution_id="2"	fishing_place_type="fishing_place_type1"	maintain_distribution_time="60"	/>
	<fishing_place	fishing_place_id="25"	territory="{{436;128216;-4764;-1764};{10168;128584;-4764;-1764};{42184;182056;-4764;-1764};{31996;197312;-4764;-1764};{680;197804;-4764;-1764}}"	limit_grid="1000"	distribution_id="2"	fishing_place_type="fishing_place_type1"	maintain_distribution_time="60"	/>
